<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>InkPlay.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.*" />
    <PackageReference Include="Markdig" Version="0.37.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InkPlay.Core\InkPlay.Core.csproj" />
  </ItemGroup>

</Project>
